Aanvragen.Web/Controllers/AttachmentController.cs
using Aanvragen.Entities;
using Aanvragen.Web.DAL;
using System;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Aanvragen.Web.Controllers {
    public class AttachmentController : Controller {
        private RequestDb db = new RequestDb();

        // GET: Attachment
        public async Task<ActionResult> Index() {
            return View(await db.Attachments.Where(x => x.Active == true).ToListAsync());
        }

        // GET: Attachment/Details/5
        public async Task<ActionResult> Details(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Attachment attachment = await db.Attachments.FindAsync(id);
            if (attachment == null) {
                return HttpNotFound();
            }
            return View(attachment);
        }

        // GET: Attachment/Create
        public ActionResult Create(string url) {
            return View();
        }

        // POST: Attachment/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Name,Description,FileName,Extention,Url,Type")] Attachment attachment) {
            if (ModelState.IsValid) {
                db.Attachments.Add(attachment);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(attachment);
        }

        // Simple MultiPart file upload form
        public ActionResult Upload() {
            return View();
        }

        // The file uploader
        public ActionResult Uploader() {
            foreach (string file in Request.Files) {
                HttpPostedFileBase hpf = Request.Files[file] as HttpPostedFileBase;

                if (hpf.ContentLength == 0)
                    continue;
                string savedFileName = Path.Combine(
                   AppDomain.CurrentDomain.BaseDirectory,
                   "UploadDir/",
                   Path.GetFileName(hpf.FileName));

                hpf.SaveAs(savedFileName);

                TempData["fileName"] = Path.GetFileName(hpf.FileName);
                TempData["fileNameLean"] = Path.GetFileNameWithoutExtension(hpf.FileName);
                TempData["Extention"] = Path.GetExtension(hpf.FileName);
                TempData["Url"] = this.Request.Url.ToString().Replace("/Attachment/Uploader", "/UploadDir/" + Path.GetFileName(hpf.FileName));
            }

            return View();
        }

        // GET: Attachment/Edit/5
        public async Task<ActionResult> Edit(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Attachment attachment = await db.Attachments.FindAsync(id);
            if (attachment == null) {
                return HttpNotFound();
            }
            return View(attachment);
        }

        // POST: Attachment/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,Name,Description,FileName,Extention,Url,Type")] Attachment attachment) {
            if (ModelState.IsValid) {
                db.Entry(attachment).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(attachment);
        }

        // GET: Attachment/Delete/5
        public async Task<ActionResult> Delete(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Attachment attachment = await db.Attachments.FindAsync(id);
            if (attachment == null) {
                return HttpNotFound();
            }
            return View(attachment);
        }

        // POST: Attachment/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id) {
            Attachment attachment = db.Attachments.Find(id);
            attachment.Active = false;
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing) {
            if (disposing) {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Aanvragen.Web/Controllers/PersonAttachmentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Aanvragen.Entities;
using Aanvragen.Web.DAL;

namespace Aanvragen.Web.Controllers {
    public class PersonAttachmentController : Controller {
        private RequestDb db = new RequestDb();

        // GET: PersonAttachment
        public async Task<ActionResult> Index() {
            var personAttachments = db.PersonAttachments.Include(p => p.Attachment).Include(p => p.Person);
            return View(await personAttachments.ToListAsync());
        }

        // GET: PersonAttachment/Details/5
        public async Task<ActionResult> Details(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PersonAttachment personAttachment = await db.PersonAttachments.FindAsync(id);
            if (personAttachment == null) {
                return HttpNotFound();
            }
            return View(personAttachment);
        }

        // GET: PersonAttachment/Create
        public ActionResult Create(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ViewBag.AttachmentID = new SelectList(db.Attachments, "ID", "Name");
            ViewBag.PersonID = new SelectList(db.People, "ID", "FirstName", id);
            return View();
        }

        // POST: PersonAttachment/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "PersonID,AttachmentID,Action")] PersonAttachment personAttachment) {
            if (ModelState.IsValid) {
                db.PersonAttachments.Add(personAttachment);
                await db.SaveChangesAsync();
                return RedirectToAction("Details", "Person", new { id = personAttachment.PersonID });
            }

            ViewBag.AttachmentID = new SelectList(db.Attachments, "ID", "Name", personAttachment.AttachmentID);
            ViewBag.PersonID = new SelectList(db.People, "ID", "FirstName", personAttachment.PersonID);
            return View(personAttachment);
        }

        // GET: PersonAttachment/Edit/5
        public async Task<ActionResult> Edit(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PersonAttachment personAttachment = await db.PersonAttachments.FindAsync(id);
            if (personAttachment == null) {
                return HttpNotFound();
            }
            ViewBag.AttachmentID = new SelectList(db.Attachments, "ID", "Name", personAttachment.AttachmentID);
            ViewBag.PersonID = new SelectList(db.People, "ID", "FirstName", personAttachment.PersonID);
            return View(personAttachment);
        }

        // POST: PersonAttachment/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,PersonID,AttachmentID,Action")] PersonAttachment personAttachment) {
            if (ModelState.IsValid) {
                db.Entry(personAttachment).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.AttachmentID = new SelectList(db.Attachments, "ID", "Name", personAttachment.AttachmentID);
            ViewBag.PersonID = new SelectList(db.People, "ID", "FirstName", personAttachment.PersonID);
            return View(personAttachment);
        }

        // GET: PersonAttachment/Delete/5
        public async Task<ActionResult> Delete(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PersonAttachment personAttachment = await db.PersonAttachments.FindAsync(id);
            if (personAttachment == null) {
                return HttpNotFound();
            }
            return View(personAttachment);
        }

        // POST: PersonAttachment/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id) {
            PersonAttachment personAttachment = await db.PersonAttachments.FindAsync(id);
            db.PersonAttachments.Remove(personAttachment);
            await db.SaveChangesAsync();
            return RedirectToAction("Details", "Person", new { id = personAttachment.PersonID });
        }

        protected override void Dispose(bool disposing) {
            if (disposing) {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Aanvragen.Web/Controllers/RequestAttachmentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Aanvragen.Entities;
using Aanvragen.Web.DAL;

namespace Aanvragen.Web.Controllers {
    public class RequestAttachmentController : Controller {
        private RequestDb db = new RequestDb();

        // GET: RequestAttachment
        public async Task<ActionResult> Index() {
            var requestAttachments = db.RequestAttachments.Include(r => r.Attachment).Include(r => r.Request);
            return View(await requestAttachments.ToListAsync());
        }

        // GET: RequestAttachment/Details/5
        public async Task<ActionResult> Details(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RequestAttachment requestAttachment = await db.RequestAttachments.FindAsync(id);
            if (requestAttachment == null) {
                return HttpNotFound();
            }
            return View(requestAttachment);
        }

        // GET: RequestAttachment/Create
        public ActionResult Create(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ViewBag.AttachmentID = new SelectList(db.Attachments, "ID", "Name");
            ViewBag.RequestID = new SelectList(db.Requests, "ID", "RequestNumber", id);
            return View();
        }

        // POST: RequestAttachment/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "RequestID,AttachmentID,Action")] RequestAttachment requestAttachment) {
            if (ModelState.IsValid) {
                db.RequestAttachments.Add(requestAttachment);
                await db.SaveChangesAsync();
                return RedirectToAction("Details", "Request", new { id = requestAttachment.RequestID });
            }

            ViewBag.AttachmentID = new SelectList(db.Attachments, "ID", "Name", requestAttachment.AttachmentID);
            ViewBag.RequestID = new SelectList(db.Requests, "ID", "RequestNumber", requestAttachment.RequestID);
            return View(requestAttachment);
        }

        // GET: RequestAttachment/Edit/5
        public async Task<ActionResult> Edit(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RequestAttachment requestAttachment = await db.RequestAttachments.FindAsync(id);
            if (requestAttachment == null) {
                return HttpNotFound();
            }
            ViewBag.AttachmentID = new SelectList(db.Attachments, "ID", "Name", requestAttachment.AttachmentID);
            ViewBag.RequestID = new SelectList(db.Requests, "ID", "RequestNumber", requestAttachment.RequestID);
            return View(requestAttachment);
        }

        // POST: RequestAttachment/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,RequestID,AttachmentID,Action")] RequestAttachment requestAttachment) {
            if (ModelState.IsValid) {
                db.Entry(requestAttachment).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.AttachmentID = new SelectList(db.Attachments, "ID", "Name", requestAttachment.AttachmentID);
            ViewBag.RequestID = new SelectList(db.Requests, "ID", "RequestNumber", requestAttachment.RequestID);
            return View(requestAttachment);
        }

        // GET: RequestAttachment/Delete/5
        public async Task<ActionResult> Delete(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RequestAttachment requestAttachment = await db.RequestAttachments.FindAsync(id);
            if (requestAttachment == null) {
                return HttpNotFound();
            }
            return View(requestAttachment);
        }

        // POST: RequestAttachment/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id) {
            RequestAttachment requestAttachment = await db.RequestAttachments.FindAsync(id);
            db.RequestAttachments.Remove(requestAttachment);
            await db.SaveChangesAsync();
            return RedirectToAction("Details", "Request", new { id = requestAttachment.RequestID });
        }

        protected override void Dispose(bool disposing) {
            if (disposing) {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Aanvragen.Web/Views/Attachment/Create.cshtml
@model Aanvragen.Entities.Attachment

@{
    ViewBag.Title = "Create";
}

<h2>Create @TempData["prefix"]</h2>


@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Attachment: @ViewBag.Url</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @Value = TempData["FileNameLean"] } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", @Value = TempData["FileNameLean"] } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FileName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FileName, new { htmlAttributes = new { @class = "form-control", @Value = TempData["FileName"] } })
                @Html.ValidationMessageFor(model => model.FileName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Extention, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Extention, new { htmlAttributes = new { @class = "form-control", @Value = TempData["Extention"] } })
                @Html.ValidationMessageFor(model => model.Extention, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control", @Value = TempData["Url"] } })
                @Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Type, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Aanvragen.Web/Views/Attachment/Delete.cshtml
@model Aanvragen.Entities.Attachment

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Attachment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FileName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Extention)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Extention)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Url)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Aanvragen.Web/Views/Attachment/Details.cshtml
@model Aanvragen.Entities.Attachment

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Attachment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FileName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Extention)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Extention)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Url)
        </dt>

        <dd>
            <a href="@Html.DisplayFor(model=> model.Url)" target="_blank">@Html.DisplayFor(model => model.Url)</a>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PersonAttachments)
        </dt>

        <dd>
            @Html.ActionLink(" ", "Create", "PersonAttachment", new { id = Model.ID }, new { @class = "glyphicon glyphicon-plus" })
            <ul>
                @if (Model.PersonAttachments != null) {
                foreach (var item in Model.PersonAttachments) {
                        <li>
                            @Html.ActionLink(" ", "Delete", "PersonAttachment", new { id = item.ID }, new { @class = "glyphicon glyphicon-minus" }) | @item.Person.FirstName @if (item.Person.Preposition != null){ @item.Person.Preposition } @item.Person.LastName - @item.Person.Role
                        </li>
                    }
                }
            </ul>

        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequestAttachments)
        </dt>

        <dd>
            @Html.ActionLink(" ", "Create", "RequestAttachment", new { id = Model.ID }, new { @class = "glyphicon glyphicon-plus" })
            <ul>
                @if (Model.RequestAttachments != null) {
                foreach (var item in Model.RequestAttachments) {
                        <li>
                            @Html.ActionLink(" ", "Delete", "RequestAttachment", new { id = item.ID }, new { @class = "glyphicon glyphicon-minus" }) | @item.Request.RequestNumber @item.Request.Name
                        </li>
                    }
                }
            </ul>
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Aanvragen.Web/Views/Attachment/Edit.cshtml
@model Aanvragen.Entities.Attachment

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Attachment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FileName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FileName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FileName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Extention, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Extention, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Extention, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Active)
                    @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Type, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Aanvragen.Web/Views/Attachment/Index.cshtml
@model IEnumerable<Aanvragen.Entities.Attachment>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Active)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Type)
        </th>
        <th>
            <div class="btn-group btn-group-xs">
                @Html.ActionLink(" ", "Create", null, new { @Class = "btn btn-success glyphicon glyphicon-link", @role = "button" })@Html.ActionLink(" ", "Upload", null, new { @Class = "btn btn-warning glyphicon glyphicon-upload", @role = "button" })
                </div>
        </th>
    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Active)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                <div class="btn-group btn-group-xs">
                    @Html.ActionLink(" ", "Edit", new { id = item.ID }, new { @class = "btn btn-primary glyphicon glyphicon-pencil", @role = "button" })
                    @Html.ActionLink(" ", "Details", new { id = item.ID }, new { @class = "btn btn-primary glyphicon glyphicon-th-list", @role = "button" })
                    @Html.ActionLink(" ", "Delete", new { id = item.ID }, new { @class = "btn btn-danger glyphicon glyphicon-trash", @role = "button" })
                </div>
            </td>
        </tr>
    }

</table>

Aanvragen.Web/Views/Attachment/Upload.cshtml
@{
    ViewBag.Title = "Upload";
}

<h2>Upload file to server</h2>
@using (Html.BeginForm("Uploader", "Attachment", FormMethod.Post, new { enctype = "multipart/form-data" })) {
    <input type="file" name="file" id="file" />
    <input type="submit" value="Upload" />
}

Aanvragen.Web/Views/Attachment/Uploader.cshtml
@{
    ViewBag.Title = "Uploader";
}

<h2>Uploader</h2>
<dl>

    <dt>
        Url:
    </dt>
    <dd>
        @ViewData["fileName"]
    </dd>
</dl>

@Html.ActionLink("Create record for this upload", "Create")